root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./backend/main.go"
bin = "tmp/server"
full_bin = "tmp/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"